const defaults = [
  {title:'Moss & Måne',creator:'Eko Studio',category:'Äventyr',color:'#ff936f',card:'#c4e86a',letter:'M',description:'En stilla vandring under en främmande måne.'},
  {title:'Riktig Rymd',creator:'S. Nyström',category:'Action',color:'#e6dcff',card:'#6951a6',letter:'R',description:'Navigera genom ett kosmiskt maskinrum.'},
  {title:'Koppla Ihop',creator:'Lilla Datorn',category:'Pussel',color:'#f9db60',card:'#ed7860',letter:'K',description:'Ett litet pussel om stora samband.'},
  {title:'Efter Regnet',creator:'Maja Ek',category:'Avkopplande',color:'#496f7e',card:'#c5e2e0',letter:'E',description:'Fånga droppar och lyssna på världen.'}
];
const grid=document.querySelector('#gameGrid'), search=document.querySelector('#search'), empty=document.querySelector('#emptyState');
let games=JSON.parse(localStorage.getItem('spelarkivet-games')||'[]').concat(defaults);
function render(filter='') { const q=filter.toLowerCase(); const visible=games.filter(g=>[g.title,g.creator,g.category,g.description].join(' ').toLowerCase().includes(q)); grid.innerHTML=visible.map((g,i)=>`<article class="game-card" tabindex="0" role="button" data-index="${games.indexOf(g)}" aria-label="Spela ${g.title}"><div class="card-art" style="--card:${g.card||g.color};--accent:${g.color}"><span class="mini">${g.category.toUpperCase()}</span><span class="big-letter">${g.letter||g.title[0]}</span><span class="shape"></span></div><div class="card-info"><h3>${esc(g.title)}</h3><p>${esc(g.creator)} · ${g.category}</p></div></article>`).join(''); empty.style.display=visible.length?'none':'block'; document.querySelector('#gameCount').textContent=String(games.length).padStart(2,'0'); }
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
render(); search.addEventListener('input',e=>render(e.target.value));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{search.value=b.dataset.filter;render(search.value);document.querySelector('#upptack').scrollIntoView()}));
grid.addEventListener('click',e=>{const c=e.target.closest('.game-card');if(!c)return;const g=games[c.dataset.index]; if(g.url) window.open(g.url,'_blank'); else alert(`${g.title}\n\n${g.description}\n\nDet här är en arkivförhandsvisning. Ladda upp en HTML-fil i adminportalen för ett spel som kan öppnas.`)});
const admin=document.querySelector('#adminDialog'), how=document.querySelector('#howDialog'), login=document.querySelector('#loginView'), upload=document.querySelector('#uploadView');
document.querySelector('#adminOpen').onclick=()=>admin.showModal();document.querySelector('#creatorUpload').onclick=()=>admin.showModal();document.querySelector('#openHow').onclick=()=>how.showModal();
const featured=document.querySelector('#featuredGame'); featured.addEventListener('click',()=>{document.querySelector('.game-card')?.click()}); featured.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();featured.click()}});
let soundOn=false; document.querySelector('#soundToggle').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'◒ LJUDBILD: PÅ':'◒ LJUDBILD: AV';};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();if(document.querySelector('#pass').value==='Vincent@12'){login.hidden=true;upload.hidden=false;document.querySelector('#pass').value=''}else document.querySelector('#loginError').textContent='Fel kod. Försök igen.'});
document.querySelector('#logout').onclick=()=>{upload.hidden=true;login.hidden=false;admin.close()};
const file=document.querySelector('#file'), zone=document.querySelector('#dropZone'), filename=document.querySelector('#fileName');
function setFile(f){if(!f)return;if(f.size>50*1024*1024){alert('Filen är större än 50 MB.');return}filename.textContent=f.name;zone.classList.add('selected')};file.onchange=()=>setFile(file.files[0]);['dragenter','dragover'].forEach(x=>zone.addEventListener(x,e=>{e.preventDefault();zone.style.background='#c6ef5d'}));['dragleave','drop'].forEach(x=>zone.addEventListener(x,e=>{e.preventDefault();zone.style.background=''}));zone.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f){const dt=new DataTransfer();dt.items.add(f);file.files=dt.files;setFile(f)}});
document.querySelector('#uploadForm').addEventListener('submit',e=>{e.preventDefault();const f=file.files[0];if(!f)return;const g={title:title.value,creator:creator.value,category:category.value,color:color.value,card:'#d9d4c7',letter:title.value[0].toUpperCase(),description:description.value};if(f.name.match(/\.html?$/i))g.url=URL.createObjectURL(f); const saved=JSON.parse(localStorage.getItem('spelarkivet-games')||'[]');saved.unshift(g);localStorage.setItem('spelarkivet-games',JSON.stringify(saved));games=[g,...games];render();admin.close();e.target.reset();filename.textContent='ELLER VÄLJ FIL';alert('”'+g.title+'” är nu arkiverat!')});
